wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1671767881.219503
    t:
      1:
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.13.7
      8:
      - 1
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 3
dataset:
  desc: null
  value: CIFAR10
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
use_amp:
  desc: null
  value: false
